#!/bin/bash
find src/components -type f -name "*.tsx" -not -name "FoodCard.tsx" | while read -r file; do
  sed -i 's/bg-blue-/bg-indigo-/g' "$file"
  sed -i 's/text-blue-/text-indigo-/g' "$file"
  sed -i 's/border-blue-/border-indigo-/g' "$file"
  sed -i 's/ring-blue-/ring-indigo-/g' "$file"
  sed -i 's/bg-purple-/bg-indigo-/g' "$file"
  sed -i 's/text-purple-/text-indigo-/g' "$file"
  sed -i 's/bg-green-/bg-emerald-/g' "$file"
  sed -i 's/text-green-/text-emerald-/g' "$file"
  sed -i 's/bg-gray-/bg-slate-/g' "$file"
  sed -i 's/text-gray-/text-slate-/g' "$file"
  sed -i 's/border-gray-/border-slate-/g' "$file"
  sed -i 's/rounded-\[32px\]/rounded-3xl/g' "$file"
  sed -i 's/rounded-t-\[32px\]/rounded-t-3xl/g' "$file"
  sed -i 's/rounded-b-\[32px\]/rounded-b-3xl/g' "$file"
  sed -i 's/rounded-l-\[32px\]/rounded-l-3xl/g' "$file"
  sed -i 's/rounded-r-\[32px\]/rounded-r-3xl/g' "$file"
  sed -i 's/rounded-\[24px\]/rounded-3xl/g' "$file"
  sed -i 's/rounded-\[20px\]/rounded-2xl/g' "$file"
  sed -i 's/rounded-\[16px\]/rounded-2xl/g' "$file"
  sed -i 's/px-\[15px\]/px-4/g' "$file"
  sed -i 's/mx-\[15px\]/mx-4/g' "$file"
  sed -i 's/px-\[10px\]/px-3/g' "$file"
done
