const fs = require('fs');
let code = fs.readFileSync('server.ts', 'utf8');
const searchStr = `        const { nutrients, itemsBreakdown } = aggregateItemsNutrients(
          rawFoodData.itemsBreakdown,
          totalWeightGrams,
          dbMatchMap,
          databaseMatchesArray,
          addDebugLog
        );`;
const replaceStr = `        // Deduplicate LLM generated itemsBreakdown to prevent duplicate macro explosion
        if (rawFoodData.itemsBreakdown && Array.isArray(rawFoodData.itemsBreakdown)) {
          const uniqueItems = [];
          const seen = new Set();
          for (const item of rawFoodData.itemsBreakdown) {
            const canonicalLower = (item.canonicalDbName || item.name || "").trim().toLowerCase();
            const weight = item.weightGrams || 0;
            const key = \`\${canonicalLower}_\${weight}\`;
            if (!seen.has(key)) {
              seen.add(key);
              uniqueItems.push(item);
            } else {
              addDebugLog(\`[Deduplication] Removed duplicate item "\${canonicalLower}" (\${weight}g) generated by Dietitian LLM.\`);
            }
          }
          rawFoodData.itemsBreakdown = uniqueItems;
        }

        const { nutrients, itemsBreakdown } = aggregateItemsNutrients(
          rawFoodData.itemsBreakdown,
          totalWeightGrams,
          dbMatchMap,
          databaseMatchesArray,
          addDebugLog
        );`;

if (code.includes(searchStr)) {
  fs.writeFileSync('server.ts', code.replace(searchStr, replaceStr));
  console.log('Deduplication logic injected.');
} else {
  console.log('Search string not found in server.ts');
}
