#!/bin/bash
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/yamlText/jsonText/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/yamlStr/jsonStr/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/yamlMsg/jsonMsg/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/yamlContext/jsonContext/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/inputsYaml/inputsJson/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/oldYamlStr/oldJsonStr/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/newYamlStr/newJsonStr/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/combinedYamlStr/combinedJsonStr/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/parseYamlOffline/parseJsonOffline/g'
find src/ server.ts -type f -name "*.ts" -o -name "*.tsx" | xargs sed -i 's/extractBiomarkerKeysFromYaml/extractBiomarkerKeysFromJson/g'
