import React, { useState, useEffect } from 'react';
import { Search, CheckCircle, ShieldAlert, Sparkles, Database, ArrowUpRight, Filter, RefreshCw, AlertTriangle } from 'lucide-react';

interface CatalogItem {
  id: string;
  food_key?: string;
  dish_key?: string;
  display_name: string;
  status: 'candidate' | 'active' | 'quarantine';
  confidence?: number;
  capture_count?: number;
  provenance?: string;
  version?: number;
  form_tags?: string[];
  nutrients_per_100g?: Record<string, number>;
  core_nutrients?: Record<string, number>;
  created_at?: string;
  updated_at?: string;
}

export function FoodCatalogAdminTab() {
  const [itemType, setItemType] = useState<'food' | 'dish'>('food');
  const [statusFilter, setStatusFilter] = useState<'all' | 'candidate' | 'active' | 'quarantine'>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [items, setItems] = useState<CatalogItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const fetchCatalog = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      const res = await fetch(`/api/admin/food-catalog?type=${itemType}&status=${statusFilter}&search=${encodeURIComponent(searchQuery)}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      setItems(data.items || []);
    } catch (err: any) {
      setErrorMsg(err.message || 'Failed to load catalog');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCatalog();
  }, [itemType, statusFilter]);

  const handlePromote = async (key: string) => {
    setActionLoading(key);
    try {
      const res = await fetch('/api/admin/food-catalog/promote', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ itemType, key })
      });
      if (!res.ok) throw new Error('Promote request failed');
      await fetchCatalog();
    } catch (err: any) {
      alert(`Error promoting item: ${err.message}`);
    } finally {
      setActionLoading(null);
    }
  };

  const handleQuarantine = async (key: string) => {
    setActionLoading(key);
    try {
      const res = await fetch('/api/admin/food-catalog/quarantine', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ itemType, key })
      });
      if (!res.ok) throw new Error('Quarantine request failed');
      await fetchCatalog();
    } catch (err: any) {
      alert(`Error quarantining item: ${err.message}`);
    } finally {
      setActionLoading(null);
    }
  };

  const candidatesCount = items.filter(i => i.status === 'candidate').length;
  const activeCount = items.filter(i => i.status === 'active').length;

  return (
    <div className="space-y-6 text-slate-800 dark:text-slate-100">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-gradient-to-r from-orange-500/10 via-amber-500/10 to-indigo-500/10 border border-orange-500/20">
        <div>
          <h2 className="text-lg font-bold flex items-center gap-2">
            <Database className="w-5 h-5 text-orange-500" />
            Food & Venues Catalog Management
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Review candidate food definitions generated by Food Resolver AI, promote validated entries to active, or quarantine erroneous items.
          </p>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <div className="px-3 py-1.5 rounded-xl bg-amber-500/15 border border-amber-500/30 text-amber-600 dark:text-amber-400 text-xs font-bold flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5" />
            <span>{candidatesCount} Candidates</span>
          </div>
          <div className="px-3 py-1.5 rounded-xl bg-emerald-500/15 border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 text-xs font-bold flex items-center gap-1.5">
            <CheckCircle className="w-3.5 h-3.5" />
            <span>{activeCount} Active</span>
          </div>
        </div>
      </div>

      {/* Control Toolbar */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        {/* Type Selector */}
        <div className="flex items-center bg-slate-100 dark:bg-slate-800 p-1 rounded-xl border border-slate-200 dark:border-slate-700">
          <button
            type="button"
            onClick={() => setItemType('food')}
            className={`px-3 py-1.5 text-xs font-bold rounded-lg transition-all cursor-pointer ${
              itemType === 'food'
                ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 shadow-sm'
                : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
            }`}
          >
            Food Items (Single Base Foods)
          </button>
          <button
            type="button"
            onClick={() => setItemType('dish')}
            className={`px-3 py-1.5 text-xs font-bold rounded-lg transition-all cursor-pointer ${
              itemType === 'dish'
                ? 'bg-white dark:bg-slate-900 text-indigo-600 dark:text-indigo-400 shadow-sm'
                : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
            }`}
          >
            Dish Core Cache (Composite Dishes)
          </button>
        </div>

        {/* Status Filter */}
        <div className="flex items-center gap-2">
          <Filter className="w-3.5 h-3.5 text-slate-400" />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as any)}
            className="px-3 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-bold focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <option value="all">All Statuses</option>
            <option value="candidate">Candidates Only</option>
            <option value="active">Active Only</option>
            <option value="quarantine">Quarantined Only</option>
          </select>
        </div>

        {/* Search */}
        <div className="flex items-center gap-2 flex-1 max-w-xs">
          <div className="relative w-full">
            <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search catalog by name..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && fetchCatalog()}
              className="w-full pl-8 pr-3 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>
          <button
            type="button"
            onClick={fetchCatalog}
            disabled={loading}
            className="p-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 rounded-xl text-slate-600 dark:text-slate-300 transition-all cursor-pointer"
            title="Refresh"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Catalog Table */}
      {loading ? (
        <div className="p-12 text-center text-xs text-slate-400 animate-pulse">
          Loading catalog items...
        </div>
      ) : errorMsg ? (
        <div className="p-6 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-rose-500 text-xs flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span>{errorMsg}</span>
        </div>
      ) : items.length === 0 ? (
        <div className="p-12 text-center text-xs text-slate-400 border border-dashed border-slate-200 dark:border-slate-800 rounded-2xl">
          No items found matching the selected filters.
        </div>
      ) : (
        <div className="overflow-x-auto border border-slate-200 dark:border-slate-800 rounded-2xl bg-white dark:bg-slate-900 shadow-sm">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 dark:bg-slate-800/50 text-slate-500 border-b border-slate-200 dark:border-slate-800">
              <tr>
                <th className="p-3 font-semibold">Display Name & Key</th>
                <th className="p-3 font-semibold">Status</th>
                <th className="p-3 font-semibold">Provenance / Version</th>
                <th className="p-3 font-semibold">Nutrients Summary</th>
                <th className="p-3 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60">
              {items.map((item) => {
                const itemKey = item.food_key || item.dish_key || item.id;
                const nutrients = item.nutrients_per_100g || item.core_nutrients || {};
                const calories = nutrients.calories ?? nutrients.energy_kcal ?? 0;
                const protein = nutrients.protein ?? 0;
                const carbs = nutrients.carbohydrates ?? 0;
                const fat = nutrients.totalFat ?? nutrients.fat ?? 0;

                return (
                  <tr key={item.id || itemKey} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors">
                    <td className="p-3">
                      <div className="font-bold text-slate-800 dark:text-slate-100">{item.display_name}</div>
                      <div className="text-[10px] text-slate-400 font-mono mt-0.5">{itemKey}</div>
                      {item.form_tags && item.form_tags.length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-1">
                          {item.form_tags.map((tag, idx) => (
                            <span key={idx} className="px-1.5 py-0.5 bg-indigo-500/10 text-indigo-500 rounded text-[9px] font-medium">
                              {tag}
                            </span>
                          ))}
                        </div>
                      )}
                    </td>
                    <td className="p-3">
                      {item.status === 'candidate' ? (
                        <span className="px-2 py-1 rounded-full bg-amber-500/15 border border-amber-500/30 text-amber-600 dark:text-amber-400 text-[10px] font-bold inline-flex items-center gap-1">
                          <Sparkles className="w-3 h-3" /> Candidate
                        </span>
                      ) : item.status === 'active' ? (
                        <span className="px-2 py-1 rounded-full bg-emerald-500/15 border border-emerald-500/30 text-emerald-600 dark:text-emerald-400 text-[10px] font-bold inline-flex items-center gap-1">
                          <CheckCircle className="w-3 h-3" /> Active
                        </span>
                      ) : (
                        <span className="px-2 py-1 rounded-full bg-rose-500/15 border border-rose-500/30 text-rose-600 dark:text-rose-400 text-[10px] font-bold inline-flex items-center gap-1">
                          <ShieldAlert className="w-3 h-3" /> Quarantined
                        </span>
                      )}
                    </td>
                    <td className="p-3 text-[11px] text-slate-500">
                      <div><span className="font-medium text-slate-700 dark:text-slate-300">Source:</span> {item.provenance || 'agent'}</div>
                      <div><span className="font-medium text-slate-700 dark:text-slate-300">Ver:</span> {item.version || 1} {item.confidence ? `| Conf: ${(item.confidence * 100).toFixed(0)}%` : ''}</div>
                    </td>
                    <td className="p-3 text-[11px] font-mono text-slate-600 dark:text-slate-300">
                      <div>{Math.round(calories)} kcal</div>
                      <div className="text-[10px] text-slate-400">P: {protein}g | C: {carbs}g | F: {fat}g</div>
                    </td>
                    <td className="p-3 text-right">
                      <div className="flex items-center justify-end gap-2">
                        {item.status === 'candidate' && (
                          <button
                            type="button"
                            onClick={() => handlePromote(itemKey)}
                            disabled={actionLoading === itemKey}
                            className="px-2.5 py-1 bg-emerald-600 hover:bg-emerald-700 active:scale-95 text-white rounded-lg text-[11px] font-bold transition-all cursor-pointer flex items-center gap-1 shadow-sm disabled:opacity-50"
                          >
                            <ArrowUpRight className="w-3 h-3" />
                            <span>Promote</span>
                          </button>
                        )}
                        {item.status !== 'quarantine' && (
                          <button
                            type="button"
                            onClick={() => handleQuarantine(itemKey)}
                            disabled={actionLoading === itemKey}
                            className="px-2.5 py-1 bg-slate-100 hover:bg-rose-500/10 hover:text-rose-600 dark:bg-slate-800 text-slate-500 rounded-lg text-[11px] font-semibold transition-all cursor-pointer disabled:opacity-50"
                          >
                            Quarantine
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
